### ISSUE TITLE
Mistake in database for Luxembourg?

### ISSUE THREAD

**Issue by dzaal** [fcambus/telize#10]
Not really a software issue,
I noticed that Luxembourg comes back from the API service with countrycode "EU" while it should be "LU".
not sure how to inform you guys about this....
I love the service and  the quality ... props for all you guys!
regards,

Dirk

**Comment by fcambus** [comment]
Just updated the public instance DB, not sure if it will fix the problem. If not, it should be reported to MaxMind. Thanks.
