### ISSUE TITLE
Get ip address through proxy

### ISSUE THREAD

**Issue by eeebb** [fcambus/telize#12]
Hi, Telize is showing Google's proxy ip address when browsed from mobile Chrome with Data Saver enabled. Is there a way to avoid that and get the real ip address of the client?

**Comment by fcambus** [comment]
Hi. Thanks for reporting this issue, according to [Data Saver](https://developer.chrome.com/multidevice/data-compression) documentation, this should be possible as client IP address is forwarded by the proxy.

**Comment by fcambus** [comment]
The C version of Telize now supports getting client IP address from the `X-Forwarded-For` headers.
