### ISSUE TITLE
Wrong timezone reported

### ISSUE THREAD

**Issue by HammyHavoc** [fcambus/telize#13]
Hi,

Currently looking at Telize within PlexPy; IP of 78.145.82.117 was parsed, the country, region and city were correct with "United Kingdom" and "Liverpool", yet the timezone was reported as "Asia/Bahrain", could you look into this for me?

Would be very much appreciated.

Thanks,
Hamual

**Comment by HammyHavoc** [comment]
Same goes for the IP of 78.109.184.243; it reckons it's Bradford in the UK, but the timezone is America/Barbados.

**Comment by fcambus** [comment]
This has been fixed in 6a25899e99a8ce7b32d46686c8b0862d0177e4f5.
