### ISSUE TITLE
Getting Wrong IP info

### ISSUE THREAD

**Issue by macray125** [fcambus/telize#17]
Hi Ma'am/Sir

I'm getting a wrong response when using telize api. Instead of I'm getting Israel the return of your API is Europe. I tried to use the https://www.whatismyip.com/ and getting the right info.

And another thing, in your Github and Telize website you are already release the version 2, why the mashape still using version1. 

https://market.mashape.com/fcambus/telize

**Comment by fcambus** [comment]
What's the IP address you are getting wrong results for?

For the transition to Telize 2 on the Mashape marketplace, detailed plan is available here: https://market.mashape.com/fcambus/telize/announcements.

**Comment by macray125** [comment]
Hi @fcambus 

This one.

![image](https://user-images.githubusercontent.com/4024193/38194334-7fcd6f7e-36a9-11e8-9b4d-cf8a4dbc8b51.png)

It should be from Israel but the API returned a wrong details. The Image below is details from https://www.whatismyip.com/ 

![image](https://user-images.githubusercontent.com/4024193/38194403-e3fa64a2-36a9-11e8-8cf1-cb9a27ba6eba.png)

**Comment by fcambus** [comment]
The database update we performed yesterday solved the issue, it now correctly returns Israel for this IP.

Also, we are now running Telize 2 on the Mashape marketplace, you can now use the new '/location' endpoint.
