### ISSUE TITLE
Procedure for updating GeoLite database

### ISSUE THREAD

**Issue by timdmackey** [fcambus/telize#19]
Hi, does telize have a built-in method for updating the geolocation database? Alternatively, what is the procedure for doing so?

GeoLite2's page notes that the database is updated monthly: https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by knife-s** [comment]
You need to make a script to be executed by a cronjob or something like that.
What I'm currently doing is updating it manually, but I know it is possible using a script and a cronjob.

**Comment by fcambus** [comment]
Please have a look at geoipupdate: https://dev.maxmind.com/geoip/geoipupdate/
