### ISSUE TITLE
Readme needs updating regarding changes to GeoLite2 license and distribution

### ISSUE THREAD

**Issue by 2shortplanks** [fcambus/telize#20]
Due to upcoming data privacy regulations, MaxMind are making significant changes to how users access free MaxMind GeoLite2 databases starting December 30, 2019. The databases will continue to be available without charge and for redistribution. However, you will be required to create an account and use a license key to download the databases, and agree to a new EULA that addresses applicable data privacy regulations.

Learn more on the MaxMind blog: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/.

Mark Fowler
MaxMind

**Comment by fcambus** [comment]
Thanks for the heads up, I will remove the links on December 30th and point to the new download instructions.

**Comment by fcambus** [comment]
Fixed in 9f36ee8d140a39a87beba3ff176b6a66f4ebec1c.
