### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [fcambus/telize#22]
I would like to point out that an identifier like “[`__H_TELIZE_H`](https://github.com/fcambus/telize/blob/64760fd818b9c94861cc674d4706fb0cb1650e6a/src/telize.h#L13 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by fcambus** [comment]
Adjusted in e3d6fee7420596af3a5b04753a5cf36190df8b61, thanks for pointing this out.

**Comment by elfring** [comment]
Thanks for [your adjustment of an affected include guard](https://github.com/fcambus/telize/commit/e3d6fee7420596af3a5b04753a5cf36190df8b61 "Renaming of an include guard").
