### ISSUE TITLE
[Feature Request] is_in_european_union

### ISSUE THREAD

**Issue by belcerca** [fcambus/telize#24]
Thanks for your great work.
Could you add an "is_in_european_union" field to the json? Sometimes the EU has some special requeriments so it would be useful to identify when an IP is from an European country.

**Comment by fcambus** [comment]
I checked and this field is present in both GeoLite2 and DB-IP Lite databases, so I see no reason to not expose it if it's present.

Commit 7bfc10e9071b70c2108bab64717d9b34f5fafa94 adds the field to the JSON output if it's present in the MMDB database used.
