### ISSUE TITLE
Issue with the powershell command 

### ISSUE THREAD

**Issue by manuelh2410** [fcambus/telize#25]
on your website it says: 
$ip = Invoke-RestMethod -Uri 'https://ip.seeip.org?format=json'
"My public IP address is: $($ip.ip)"

The command should be : 

$ip = Invoke-RestMethod -Uri 'https://ip.seeip.org?format=json'
"My public IP address is: $($ip)"

**Comment by fcambus** [comment]
It seems SeeIP is indeed using Telize, but you would have to raise the issue to them directly, I'm not affiliated to them in any way.
