### ISSUE TITLE
https://api.seeip.org/ returns 502 !!!

### ISSUE THREAD

**Issue by mohamedbrahimi** [fcambus/telize#31]
am trying to call GET  https://api.seeip.org/  but it responding by 502!!

**Comment by sumanrajpathak** [comment]
Getting the same error since 2 days.

**Comment by modernben** [comment]
Down again

**Comment by fcambus** [comment]
It seems the issue you’re experiencing is related to a downstream service. Please note that I am not affiliated with this service and do not have control over its operations.

**Comment by modernben** [comment]
Appreciate the response and apologies for the mixup
