### ISSUE TITLE
HTTPS functionality

### ISSUE THREAD

**Issue by apcrane** [fcambus/telize#8]
Hi, the Telize GeoIP plugin works very well and very easy to use. However, now Google is placing higher priority on indexing websites that are HTTPS, are there any plans to make it available under a SSL so that websites running on HTTPS can use this web service?

I look forward to your reply.

Many thanks

**Comment by fcambus** [comment]
Yes, it's in the work, and already accessible : https://www.telize.com/geoip/

Please test and report issues if any.

**Comment by apcrane** [comment]
Hi Frederic,

Thanks for getting back to me, this all appears to working and has allowed me to remove my work around.

Many thanks
Andy

**Comment by fcambus** [comment]
Great! Nice to hear it works as intended :)
